- type: entity
  parent: BaseClothingLegs
  id: STOWBaseClothingJumpsuit # Clothing that takes up both the torso and legs slot.
  suffix: STOW
  abstract: true
  components:
  - type: Tag
    tags:
      - BlockTorso
